# Fuente de la verdad para los despliegues en Netlify.
# Lo aquí configurado prevalece sobre la UI.

[build]
  publish = "httpdocs"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "22"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
